import { createHash } from 'node:crypto';
import { Prisma } from '@prisma/client';
import { database, disconnectDatabase } from '@quran-hajrah/database';

type Candidate = {
  severity: 'MEDIUM' | 'HIGH' | 'CRITICAL';
  title: string;
  description: string;
  sourceRecordId: string;
  dueDate?: Date | null;
  kind: string;
};

const fingerprint = (candidate: Candidate) =>
  createHash('sha256')
    .update(`document-analysis|${candidate.kind}|${candidate.sourceRecordId}`)
    .digest('hex');

const main = async () => {
  const now = new Date();
  const [failed, overdueReview, approvedNotImported, unresolvedConflicts] = await Promise.all([
    database.documentAnalysisJob.findMany({
      where: { deletedAt: null, status: 'FAILED' },
      select: { id: true },
    }),
    database.documentAnalysisJob.findMany({
      where: {
        deletedAt: null,
        status: { in: ['PROPOSALS_READY', 'UNDER_REVIEW', 'PARTIALLY_APPROVED'] },
        reviewDueAt: { lt: now },
      },
      select: { id: true, reviewDueAt: true },
    }),
    database.documentAnalysisJob.findMany({
      where: { deletedAt: null, status: 'APPROVED' },
      select: { id: true },
    }),
    database.extractionImportItem.findMany({
      where: { status: 'SKIPPED', conflict: { not: Prisma.JsonNull } },
      select: { id: true },
    }),
  ]);

  const candidates: Candidate[] = [
    ...failed.map((job) => ({
      severity: 'HIGH' as const,
      title: 'تعثر تحليل مستند',
      description: 'توجد مهمة تحليل متعثرة تحتاج إلى مراجعة سجل المهمة وإعادة المحاولة.',
      sourceRecordId: job.id,
      kind: 'failed',
    })),
    ...overdueReview.map((job) => ({
      severity: 'MEDIUM' as const,
      title: 'تأخر مراجعة مقترحات مستند',
      description: 'تجاوزت مهمة التحليل مدة المراجعة المحددة في الإعدادات.',
      sourceRecordId: job.id,
      dueDate: job.reviewDueAt,
      kind: 'review-overdue',
    })),
    ...approvedNotImported.map((job) => ({
      severity: 'MEDIUM' as const,
      title: 'مقترحات معتمدة لم تُستورد',
      description: 'توجد مقترحات معتمدة بانتظار معاينة التعارضات والاستيراد.',
      sourceRecordId: job.id,
      kind: 'approved-not-imported',
    })),
    ...unresolvedConflicts.map((item) => ({
      severity: 'HIGH' as const,
      title: 'تعارض استيراد يحتاج إلى قرار',
      description: 'تخطي الاستيراد تعارضًا ويتطلب قرارًا بشريًا قبل إعادة المحاولة.',
      sourceRecordId: item.id,
      kind: 'import-conflict',
    })),
  ];

  for (const candidate of candidates) {
    const key = fingerprint(candidate);
    await database.executiveAlert.upsert({
      where: { fingerprint: key },
      update: {
        severity: candidate.severity,
        title: candidate.title,
        description: candidate.description,
        dueDate: candidate.dueDate,
        status: 'OPEN',
        deletedAt: null,
      },
      create: {
        severity: candidate.severity,
        status: 'OPEN',
        title: candidate.title,
        description: candidate.description,
        sourceModule: 'document_analysis',
        sourceRecordId: candidate.sourceRecordId,
        fingerprint: key,
        dueDate: candidate.dueDate,
        isAutoGenerated: true,
      },
    });
  }
  console.log(
    JSON.stringify({
      event: 'document_analysis_alert_generation_completed',
      generatedOrUpdated: candidates.length,
    }),
  );
};

main()
  .catch((error) => {
    console.error(
      JSON.stringify({
        event: 'document_analysis_alert_generation_failed',
        errorName: error instanceof Error ? error.name : 'UnknownError',
      }),
    );
    process.exitCode = 1;
  })
  .finally(() => disconnectDatabase());
